name: docker-build

on:
  pull_request:
  push:
    branches:
      - "main"
    tags: ["**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/checkout@v3

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push
        run: |
          cd images/
          ./build.py --push
